kind = "web"
previewPath = "/"
title = "Utility 1"
version = "1.0.0"
id = "artifacts/utility1"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19303

[services.development]
run = "pnpm --filter @workspace/utility1 run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/utility1", "run", "build" ]
publicDir = "artifacts/utility1/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19303"
BASE_PATH = "/"
